<?php /** @var $block \Magento\Checkout\Block\Cart\Shipping */ ?>
<?php /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */ ?>
<?php $serializedCheckoutConfig = /* @noEscape */ $block->getSerializedCheckoutConfig();

$scriptString = <<<script
    window.checkoutConfig = {$serializedCheckoutConfig};
    window.customerData = window.checkoutConfig.customerData;
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    require([
        'mage/url',
        'Magento_Ui/js/block-loader'
    ], function(url, blockLoader) {
        blockLoader(
            "{$block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')))}"
        );
        return url.setBaseUrl('{$block->escapeJs($block->escapeUrl($block->getBaseUrl()))}');
    })
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>