<?php
// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\Affiliate\Block\Container */
?>

<div data-role="<?php /* @noEscape */ echo $block->getDataRole() ?>"
     data-bind="scope: '<?php /* @noEscape */ echo $block->getScopeForDataBind() ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "[data-role=<?php /* @noEscape */ echo $block->getDataRole() ?>]": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>
        }
    }
</script>
<style>
.field._required[name="data.terms_and_conditions"] .label span {
    display: none;
}
.field._required[name="data.terms_and_conditions"] .admin__field.admin__field-option {
    display: none;
}
.aw-aff__wrapper-fieldset .fieldset .choice.field {
    margin-top: -50px;
    padding-bottom: 20px;
}
.aw-aff__signup-form .control._with-tooltip .field-error {
    bottom: -45px;
}
.field._required[name="data.terms_and_conditions"]>.label:after {
    margin-left: 230px;
}
.aw-aff__wrapper-fieldset .fieldset .choice.field span{
    font-weight: 600;
}
</style>
